### ISSUE TITLE
on OpenBSD 6.4, gmake needed to build

### ISSUE THREAD

**Issue by andy5995** [bbonev/yascreen#1]
I couldn't build yascreen until I ran `gmake` instead of `make`. With `make`, I get this output:

```
*** Parse error in /home/andy/src/Vfu/vfu-dist/yascreen: Missing dependency operator (Makefile:30)
*** Parse error: Need an operator in 'else' (Makefile:32)
*** Parse error: Missing dependency operator (Makefile:33)
*** Parse error: Need an operator in 'else' (Makefile:35)
*** Parse error: Need an operator in 'endif' (Makefile:37)
*** Parse error: Need an operator in 'endif' (Makefile:38)
*** Parse error: Missing dependency operator (Makefile:41)
*** Parse error: Missing dependency operator (Makefile:42)
*** Parse error: Need an operator in 'endif' (Makefile:44)
*** Parse error: Need an operator in 'endif' (Makefile:49
```

I'm pretty new to BSD so not sure if BSD users already know to run `gmake`, or if the yascreen docs should contain the info.

**Comment by bbonev** [comment]
Makefile was never intended to be used with BSD make but with gmake on *BSD.

I would suppose that splitting the configuration part in BSDmakefile and GNUmakefile both of which include Makefile.common will solve the problem in quite a portable way without having to duplicate stuff and track the changes in two separate files.

A pull-request on this is welcome

**Comment by andy5995** [comment]
> A pull-request on this is welcome

I'd be happy to, but I don't know the differences between makefiles compatible with GNU Linux and BSD, and I'm mostly just familiar with automake files.
