### ISSUE TITLE
Outdated Slackbuild

### ISSUE THREAD

**Issue by andy5995** [bbonev/yascreen#8]
You might wanna see if you can get this updated...

https://slackbuilds.org/repository/15.0/libraries/yascreen/?search=yascreen

**Comment by bbonev** [comment]
I don't maintain the SlackBuild...

@Ponce Maybe you can look into that?

**Comment by Ponce** [comment]
np, it will go into next weekend's update!

**Comment by bbonev** [comment]
Looks like done since long ago, thanks!
